### ISSUE TITLE
Possible species name spelling issues

### ISSUE THREAD

**Issue by skybristol** [usgs-bcb/gap_species#16]
I'm working to finish out an initial version of the Taxa Information Registry process for GAP species that we will talk about in a couple weeks when we hopefully get together in person. I'll be working to document a number of areas where we might improve on the GAP species information as I run through this. I just ran through a new process that checks GAP information against ITIS, using TSNs when you all identified them and name lookups when you did not. This [notebook](https://github.com/usgs-bcb/gap_species/blob/master/GAP%20Species%20with%20possible%20scientific%20name%20changes.ipynb) shows 6 GAP species where we were not able to get an exact match on scientific name.

The notebook attempts a fuzzy match against ITIS, and for 3 of the names, it does return a single match. It looks like these could be alternative Latin spellings of scientific names or names that changed since the GAP species information was started.

For this process, I'm treating the still private [ScienceBase collection](https://www.sciencebase.gov/catalog/item/527d0a83e4b0850ea0518326) as the authoritative point of reference now for GAP species information. The TIR processing code gets scientific names, species codes, and all other information about GAP species from the 1719 items in that collection. So, if we decide to change scientific names for these three, we should do so on the items in that collection. I added the ScienceBase Item links to the report in the notebook output so that these can be easily accessed if someone wants to make a change.

Please add a comment to this issue to let me know what we do to resolve it, and I'll re-run things in the TIR to update information.

**Comment by SGWilliams** [comment]
**rDHNSx**:  A distinct species according to Crother (2012). Also recognized by NatureServe. Range proved distinct from the _H. nasicus_ complex from whence it was derived. Valid ITIS matching concept is the subspecies: _Heterodon nasicus gloydi_ TSN 209163.

**aSENEx**:  A direct match on scientific name to a valid ITIS concept: _Taricha sierrae_ TSN 775939. The valid ITIS concept does not have a common name listed. Rather, an invalid subspecies concept has that associated common name. (_Taricha torosa sierra_ TSN 208227).

**rYBSLx**:  A distinct species according to Crother (2012). A distinct species range described in Leache and Mulcahy (2007). Valid ITIS matching concept is the subspecies: _Sceloporus magister uniformis_ TSN 208752.

**mELK1r**:  ITIS is not only behind the recent split of N.A. elk from other global populations as _Cervus canadensis_, but is also unclear on which recognized subspecies Roosevelt elk are combined with (either Tule elk/_C. elaphus nannodes_ or Rocky Mtn elk/_C. e. canadensis_). The following text is from IUCN (http://www.iucnredlist.org/details/55997823/0):
---------------
The North American population of the Wapiti has been split into a number of subspecies by various authors, including _manitobensis, nelsoni, roosevelti, nannodes, canadensis and merriam_ (e.g. Meredith et al. 2007, Speller et al. 2014). Polziehn et al. (1998) conducted a phylogenetic study of North American Wapiti and concluded that there is a slight difference between North American Wapiti populations, most likely due to the limited numbers of founders of these populations, but that Roosevelt Elk (_Cervus canadensis roosevelti_) and Tule Elk (_C. c. nannodes_) are monophyletic which supports their subspecific status. Polziehn et al. (2000) questioned the subspecific status of _C.c. manitobensis_ and _C. c. nelsoni_ following analysis of 11 populations of North American Elk for genetic diversity. 

Here we recognise the subspecies and their distributions as follows: 

_C. c. canadensis_ – N America
_C. c. alashanicus_ – N China
_C. c. nannodes_ - California
_C. c. roosevelti_ - Vancouver Island, Washington state and Oregon 
_C. c. sibiricus_ – NE Kazakhstan and N Xinjiang to S Siberia and N Mongolia
_C. c. xanthopygus_ – SE Siberia, Russian Far East, Ussuriland, Manchuria
_C. c. macneilli_ – Lydekker 1909 (Central and SW China (N Qinghai, Gansu, Shaanxi, W Sichuan and E Xizang)
_C. c. wallichii_ - G. Cuvier 1823 (SW China (SE Xizang), Bhutan)
---------------
 We choose to diverge from ITIS on this complex due to the inherent conservation/management focus on elk.

**mSEWEo**:  Piaggio et al. (2013) recognized and mapped a distinct range for the Olympic mountain beaver. ITIS does not recognize that subspecies and instead, includes it in _Aplodontia rufa rufa_ TSN 202350 (which GAP also recognizes as a sub-species **mSEWEr**).

**mMARAh**: A direct match on scientific name to a valid ITIS concept: _Sylvilagus palustris hefneri_ TSN 202349.


CITATIONS:
Crother, B. I. (ed.) 2012. Standard Common and Current Scientific Names for North American Amphibians, Turtles, Reptiles, and Crocodilians, Seventh Edition. Herpetological Circular 39: 1-92. 

Leache, A.D. and D.G. Mulcahy. 2007.  Phylogeny, divergence times and species limits of spiny lizards (Sceloporus magisterspecies group) in western North American deserts and Baja California.  Molecular Ecology 16:5216-5233  

Piaggio, A. J., B. A. Coghlan, A. E. Miscampbell, W. M. Arjo, D. B. Ransome, and C. E. Ritland. 2013. Molecular phylogeny of an ancient rodent family (Aplodontiidae). Journal of Mammalogy 94:529-543.

Wilson, Don E., and DeeAnn M. Reeder, eds. 2005. Mammal Species of the World: A Taxonomic and Geographic Reference, 3rd ed., vols. 1 & 2. 2142.

**Comment by skybristol** [comment]
Fantastic! That's exactly the sort of reasoning I'm interested in.

I'll look at a way that we can capture these kinds of notes within the overall Taxa Information Registry architecture. The goal in what I've been doing has not been to force alignment with ITIS or any taxonomic information source, but rather to systematically and periodically identify and document connections and divergences so that we can a) make the dynamics clear to any users of our data and analytical products and b) evaluate changes in underlying information sources to decide if there is any action needed within our processes.

**Comment by skybristol** [comment]
Also, your point on the Dusty Hog-nosed Snake about NatureServe recognizing the species is a good one for me to consider. I've built a process to pull information into the Taxa Information Registry from the NatureServe API. The identifier the service needs to run is the NatureServe Element Global ID. Currently, I use the scientific name in the open, public query to find the Element Global ID and then use that with a secure service using an API Key we have from NatureServe to retrieve other information. The GAP species data includes a "NatureServe Element Code," but I haven't yet figured out how to turn that into the Element Global ID that the web service needs.

Right now, I've only been pulling the conservation status information - global, US national, and US subnational (state) - because we've been experimenting more with comparing Federal and State listing status with NatureServe/Heritage Foundation conservation status. I have not been grabbing other information on taxonomic concepts, distribution, or other attributes from NatureServe. However, it sounds like the GAP team is sometimes using what NatureServe has on taxonomy and species concepts as part of the basis for the GAP species records, so we should look at bringing in some of that additional information for use.

Since the GAP species are associated with an identifier from NatureServe (meaning you all did the work on linking the species to a particular NatureServe record), I'll figure out how to pull that record with the API vs. using the scientific name for a lookup. That will pull the specific record that should be associated with a GAP species.

**Comment by SGWilliams** [comment]
The GAP species list is really a custom list - not entirely identical to either ITIS or NatureServe. If memory serves me, we have more mismatches with NS codes than we do with ITIS (invalids notwithstanding). We also have the NS Element Global ID in our dB. Sounds like I should revisit that key list I provided to you earlier where we had GapSppCode, ComName, SciName, ItisTSN and swap out the NS Element Code for the NS_Global_ID. I will also pull together the TSN divergent comments I just sent as well as other comments that may be scattered to several fields in our dBs for any of the invalid TSNs identified and get that into a new designated field.

**Comment by skybristol** [comment]
If you want to provide a text file with NS_Global_ID matched to GAP_SpeciesCode, I'll write something that will add the NS_Global_ID as an additional identifier to the species records in ScienceBase. If you can attach the file right to [this item](https://www.sciencebase.gov/catalog/item/527d0a83e4b0850ea0518326), that would be great. Let me know it's there, and I'll script the process to add the IDs.

I do get that the set of 1719 GAP species are their own unique entities. They are registered into the Taxa Information Registry as such. The processes that we are talking about here are not about aligning them with ITIS or any other list. Rather, the processes in the TIR find points of reference and build linkages to additional information that our various data management and analysis activities can leverage. We'll look more closely at this in a couple of weeks when we get together, but each information source (ITIS, WoRMS, FWS TESS, NatureServe - and coming up, IUCN Red List, EoL Traitbank, and others) becomes a structured document linked to a GAP Species record based on a software process that either uses the identifier to retrieve available information or uses scientific name to establish a point of potential reference. We then decide how we use the properties in those documents to good effect within the overall Biogeographic Information System, and that depends on the meaning and significance of the link between GAP species and associated information. If there is a tight connection between the GAP species and something like ITIS, meaning that someone made a call to trust and adopt the particular ITIS taxonomy for the species concept we are modeling and analyzing, then we use it one way. If it's a loose connection that has not been validated, then we treat ITIS as a point of reference for further study down the road somewhere (e.g., the 128 GAP species with ITIS TSNs that ITIS thinks are now invalid).

**Comment by SGWilliams** [comment]
Sounds like we're on the same page with the list associations concept. I'll
be on vaca for the rest of the week but when I return I'll work on updating
the ScienceBaseCSV file that Nathan initially provided. In addition to
adding NS Global ID, there's been a lot of work rectifying the Model Editor
and Model Reviewer fields.

Steve Williams
Biodiversity and Spatial Information Center
NC Cooperative Fish & Wildlife Research Unit
Department of Applied Ecology
North Carolina State University
Campus Box 7617
Raleigh, NC  27695-7617
(919) 513-7413 ph.
(919) 515-4454 fax
steve_williams@ncsu.edu
www.basic.ncsu.edu

**Comment by skybristol** [comment]
Great! We'll use the opportunity to work up a more thorough update for the contact information as well, then. Thanks, and have some great time away.

**Comment by SGWilliams** [comment]
Here is the list of vetted NS Global IDs along with ITIS TSNs. We do have a number of invalid TSNs still in the mix and they are intended. In addition, we have some mismatches of concepts that actually point to a valid TSN (i.e. GAP has a subspecies that ITIS never recognized and we're pointing to the valid ITIS species it was derived from). We also have several mismatches for NS Global IDs. We are acknowledging these invalids and mismatches with 0/1 checkbox fields for both NS and ITIS. 

"1" denotes both a valid TSN and a match of concept. 
"0" denotes either an invalid TSN or a mismatch of concept. 

NS does not present "invalids" so in that case we are just noting a correct/incorrect match of species concept. 

Sky, if you could run the previous script where you were finding invalid TSNs against the attached list, then we could confirm the invalids we still have. There may be more in the list - I only checked those that had duplicates from the first effort. 

You could also point out where the script currently is and I'll give it a shot.

[Gap_NS_ITIS_codes.zip](https://github.com/usgs-bcb/gap_species/files/1380700/Gap_NS_ITIS_codes.zip)

**Comment by skybristol** [comment]
Okay. It's really a matter of getting the data right for the GAP species items in the habitat maps collection in ScienceBase, and then re-running the whole sequence of Taxa Information Registry processes based on this new information.

It seems like we are going to need to get a little more sophistication in how this information is represented in the ScienceBase Items. We can do that somewhat legitimately by using the scheme in the identifier construct against an a specific vocabulary term denoting the various "meanings" of an ITIS TSN and NS Global ID being assigned to a GAP species item. That will change things in terms of how the TIR reads and processes the information, so all that code will have to follow along with the added complexity.

It seems like we would maybe eventually want to break out the "0" value concept for ITIS where we have both of those options, unless you meant to indicate that we recognize the TSN as being invalid and that there is a mismatch of species concept. It also seems like we might want to have a special case for when we are pointing to a higher level taxonomic name (e.g., species) that is used as a reference for a lower level concept that ITIS does not yet recognize (or hasn't done the work on).

**Comment by skybristol** [comment]
I took a first crack at defining the identifiers we will have on the GAP species items and others as part of a vocabulary [here](https://www.sciencebase.gov/vocab/bis_identifiers/terms). While ScienceBase is very much a less than optimal solution for vocabularies, it does at least give us a simple reference point and unique, persistent identifiers for terms that we can reference. @SGWilliams, if you can take a look at the definitions for these concepts to see if they accurately capture the intent of the different ways you are linking ITIS TSNs and NatureServe Element IDs to GAP species, that would be great. Let me know where I went wrong in the definitions.

**Comment by SGWilliams** [comment]
Yes, the cbxITISvalidMismatch "0" are complex and it will take more fields to nail it all down. I just tried to limit the mission creep but we can rework that if it makes sense at this point.  Looks like you're building that into the vocabulary you set up. 

I will run through the 59 ITIS "0" and characterize the nature of each type of mismatch. That will help define what fields/definitions we'll need to capture the true nature of the mismatch.

**Comment by SGWilliams** [comment]
Here's the breakdown of mismatched GAP-ITIS species' concepts.

**#     Description**
22	ITIS does not recognize a recent genus reassignment. Link is to the valid species with old name.
04	ITIS does not recognize this spp concept. Link is to a valid spp concept that encompasses this spp.
01	ITIS does not recognize this sub-population concept. Link is to the valid species.
27	ITIS does not recognize this subspecies concept. Link is to the valid species.
04	ITIS recognizes this species concept as a subspecies. Link is to the valid subspecies.
01	ITIS recognizes this subspecies concept as a species. Link is to the valid species.

This is with me digging into the literature in a shallow nature and try to discern if the species concept has shifted other than in name/hierarchy. Specifically, did the known range change along with the name change. In most cases, it does not appear to have, but that's not a guarantee. We feel like if someone were to gather info through one of these relates (GAP-ITIS or GAP-NS), then they ought to have a heads up on what that relationship status is.

Note that even when it appears that a concept has moved entirely from a subspecies to a species (or vise-versa), we are choosing to keep the original taxonomy we had. We need to do this due to the fact that our species richness numbers are built on the current taxonomy. We simply don't have the time right now to break those apart and re-run. 

Instead of building fields/definitions to define the relationship, we can probably just include the text above.

**Comment by skybristol** [comment]
This has been resolved through the work with @SGWilliams on defining the specified connection of ITIS TSN to GAP species. The vocabulary terms for the IDs on both habitat and range map items are now complete.
