### ISSUE TITLE
Fix "ERROR" values in species model reports

### ISSUE THREAD

**Issue by skybristol** [usgs-bcb/gap_species#35]
After the latest round of building in the habitat map model report JSON files, I'm still noticing some with "ERROR" values in references.

E.g., https://www.sciencebase.gov/catalog/item/58fa6037e4b0b7ea545256d2

It seems to me that we don't want to release these that way. Can we come up with a fix to whatever is wrong in the data so that we don't write ERROR into the reports? Alternatively, if the data are too messy to fix at this time, should we simply leave out references that we can't deal with and come back to that problem later?

**Comment by nmtarr** [comment]
I will look into this.  My first thought is that there will be an easy fix.

**Comment by SGWilliams** [comment]
One of the errors I did find when I ran the script was a Spanish accent on a word in the habitat description field. I "gringo-ed" the spelling and it ran fine afterwards.

**Comment by nmtarr** [comment]
I've been looking into these errors and there's a string encoding issue that's especially problematic with apostrophes.   I could do a quick, dirty fix and drop offending characters, but I'm going to continue working on a real solution on Monday.   I found some simple approaches for these situations online but none of them have actually worked for me.

**Comment by nmtarr** [comment]
I haven't been able to fully overcome this decoding issue, but I changed the code so that the "ERRORS" don't show up any more and instead include the offending citations' text.  Unfortunately, the text is unicode with "\u2019" in place of apostrophes; although the apostrophes show up if the text is printed.  I'm at a loss for what to do to fix this issue (or about unicode in general) but I went ahead and updated all the habmap json documents after replacing the "ERROR's".

**Comment by skybristol** [comment]
@nmtarr, I've looked through a number of the reports. I think they are fine at this point. There are a number of other encoding nuances in the longer habitat description write-ups as well. I think we can deal with those down the road. The important thing is getting the information out there at this point, and what you have there now does that just fine. Thanks for getting these all working.
