### ISSUE TITLE
Work up code for generating GAP species range items

### ISSUE THREAD

**Issue by skybristol** [usgs-bcb/gap_species#4]
We've decided that each species range should be individually referenceable with a URI and citable with a DOI just like the habitat maps/models. Someone needs to work over Daniel's code for building the items and minting DOIs to run that for the [range collection](https://www.sciencebase.gov/catalog/item/5951527de4b062508e3b1e79). Alternatively, we could simply use the 1719 items in the [habitat distribution maps collection](https://www.sciencebase.gov/catalog/item/527d0a83e4b0850ea0518326) to derive new items for the ranges on those species.

**Comment by SGWilliams** [comment]
I'm at a point where I need the individual range DOIs. Can someone point me to the code Daniel was using to mint them?

**Comment by skybristol** [comment]
I'm going to clean up and run the code for minting the DOIs on the range items in ScienceBase as soon as I'm able to dig into it. The code needs a little love as it introduced newline and trailing spaces to the DOIs previously that had to be cleaned up. I ran through a number of steps yesterday to clean up the habitat map items that we'll use as a pattern for the range items. This included contact, identifier, and citation string tweaks . I still need to run through your spreadsheet of ITIS/NS codes and add those in with appropriate vocabulary URIs indicating their intended purpose. Once that's done, we'll have everything in place to crank out the 1719 range items including minting those DOIs.

@SGWilliams, why do you need the DOIs on your end at this point?

**Comment by SGWilliams** [comment]
I'm about to put out the updated HapMap CSV for SB items and it seems like a good place to put a link to the Range SB item (and vis-versa). Also looking to embed the range DOI link in the HabMap reports.

I also have some updates to the previous list of ITIS/NS codes. Specifically, as I went through characterizing each mismatch I replaced all the invalid TSNs with valid codes figuring the explanation on how they're related needs to go along with it (at least I think I got all the invalids). 

I've moved away from a 0/1 indicator to 0-6 with a lookup table for definitions (see below). I will include the text definition into the SB item CSVs. The wording is different because ITIS uses "valid" whereas NS uses "accepted". 


intGapITISmatch | strGapITISmatch
-- | --
0 | ITIS valid match.
1 | ITIS recognizes this subspecies concept as a species. Link is to the   valid species.
2 | ITIS recognizes this species concept as a subspecies. Link is to the   valid subspecies.
3 | ITIS does not recognize a recent genus reassignment. Link is to the valid   species with former name.
4 | ITIS does not recognize this subspecies concept. Link is to the valid   species.
5 | ITIS does not recognize this sub-population concept. Link is to the valid   species.
6 | ITIS does not recognize this species concept. Link is to a valid species   concept that encompasses this species.


intGapNSmatch | strGapNSmatch
-- | --
0 | NatureServe accepted match.
1 | NatureServe recognizes this subspecies concept as a species. Link is to   the accepted species.
2 | NatureServe recognizes this species concept as a subspecies. Link is to   the accepted subspecies.
3 | NatureServe recognizes a recent genus reassignment. Link is to the   accepted species with new name.
4 | NatureServe does not recognize this subspecies concept. Link is to the   accepted species.
5 | NatureServe does not recognize this sub-population concept. Link is to   the accepted species.
6 | NatureServe does not recognize this species concept. Link is to an   accepted species concept that encompasses this species.

I think I finally got my forked repository setup correctly - you should see a pull request for the updated list of codes.

**Comment by skybristol** [comment]
Fantastic! This is great. I will put these concepts into the vocabulary that I referenced elsewhere and build a script to tie ITIS TSNs and NatureServe IDs to the appropriate usage on the habitat map items. That should complete the information that we will use as a pattern for generating the range items, and we can proceed with that.

I'm going to close out this issue to help keep the record straight.
